### ISSUE TITLE
Deployment in yaml folder is broken

### ISSUE THREAD

**Issue by StellaASchlotter** [zakkg3/ClusterSecret#102]
There is an error in the yaml https://github.com/zakkg3/ClusterSecret/blob/master/yaml/02_deployment.yaml

The env part should go under spec.template.spec.container.name and not under spec.template.spec

The helm chart looks correct but I havent tried that yet.

**Comment by zakkg3** [comment]
dankeshön for reporting.
can you open a PR ? that would be great!

thanks!!
