### ISSUE TITLE
Missing config toleration and nodeSelector in HELM chart

### ISSUE THREAD

**Issue by cedvan** [zakkg3/ClusterSecret#119]
Hi,

I want to replace my old manual YAML with this new helm chart. But I need to configure node selector and tolerance for deployment on my infrastructure.

So I'm stuck. I think this would be a good new feature for helm chart.

**Comment by zakkg3** [comment]
@cedvan can you test [this branch](https://github.com/zakkg3/ClusterSecret/tree/fix_chart) and deploy the chart with tolerations and affinities and let me know how it goes?

**Comment by cedvan** [comment]
But last update create this problem : https://github.com/zakkg3/ClusterSecret/issues/126
