### ISSUE TITLE
Issue applying ClusterSecret manifest using ArgoCD after updating to 0.0.10

### ISSUE THREAD

**Issue by PurseChicken** [zakkg3/ClusterSecret#126]
I believe the issue has to do with the CRD scope change from being Namespaced to Cluster... but I could be totally wrong.

I updated from 0.0.9 using helm chart  0.2.1 to 0.0.10 using helm chart 0.4.1. I could not sync the CRD, since the scope field is immutable. So I deleted my clustersecret resources, and deleted the old CRD. Then I could successfully sync and everything appeared to be good.

I tried syncing one of my cluster-secret resources, and it would fail in Argo. I kept getting the error:

`one or more objects failed to apply, reason: the server could not find the requested resource (post clustersecrets.clustersecret.io)`

I could manually `kubectl apply -f` the exact same yaml file and that would work, however syncing from argo seemed to indicate it could not validate the CRD.

I rolled back to 0.0.9 and rolled back the CRD and everything started working again as expected.

**Comment by cedvan** [comment]
Same here

**Comment by cedvan** [comment]
So Rollback to helm chart version 0.4.0

**Comment by zakkg3** [comment]
fixed here https://github.com/zakkg3/ClusterSecret/pull/147

**Comment by trashhead** [comment]
I have tried different versions but I cannot get it to work, I keep getting: 

> one or more objects failed to apply, reason: the server could not find the requested resource (post clustersecrets.clustersecret.io)

What chart version is it solved in and is there other changes I need to do?
