### ISSUE TITLE
Incorrect scope

### ISSUE THREAD

**Issue by sftim** [zakkg3/ClusterSecret#13]
https://github.com/zakkg3/ClusterSecret/blob/30d994935cc92e957f80da4c9110daf24199e7d2/yaml/01_crd.yaml#L7 shows that ClusterSecret is namespaced. Surely it should be cluster scoped?

**Comment by zakkg3** [comment]
The CRD ClusterSecret is namespaced. The object belongs to a namespace from where the operator  sync (it keeps a copy of the secret on the matching namespaces as far as the object exist)  the secret to where it matches.  It also d

**Comment by zakkg3** [comment]
@sftim check this commit :e707159bf7fad1cfbea81b3d8102081dcbea4e5a

**Comment by sftim** [comment]
Interesting. I feel that if there were a Kubernetes official CRD named ClusterSecret, that official CRD couldn't be namespaced as it would be too confusing. However, I understand that this CRD has a different design.
