### ISSUE TITLE
[feature] ARM64 support

### ISSUE THREAD

**Issue by devantler** [zakkg3/ClusterSecret#131]
Hey, I would like to ask for ARM64 support for the Helm Chart. Currently it is not supported:

`failed to pull and unpack image "quay.io/clustersecret/clustersecret:0.0.10": no match for platform`

**Comment by devantler** [comment]
For now it seems possible to use the alt image:

```yaml
values:
  image:
    tag: alt-0.0.10
```

However this is outdated compared to the latest image, and I still think it would be nice if the latest image includes the arm support.

**Comment by zakkg3** [comment]
Please pull v0.0.11 or install chart 0.4.3:

```
helm repo add clustersecret https://charts.clustersecret.com/
helm install clustersecret clustersecret/cluster-secret --version 0.4.3 -n clustersecret --create-namespace
```


Archs available:
```
SHA256 ed12e8f3e630 | linux | 386
SHA256 91b0285f5398 | linux | amd64
SHA256 cad79c68cb8c | linux | s390x
SHA256 637f3be7850a | linux | arm64
```


https://quay.io/repository/clustersecret/clustersecret/manifest/sha256:3e5448773a36aeb8e56db5b03cd4851bb7a8f8eb8e818f9e467c0dbbf3088626

Armv7 is not supported anymore,. it requires build essential.
if someone needs v7 open an issue and I can provide an alternative tag for this.
Details here: https://github.com/zakkg3/ClusterSecret/actions/runs/11042078300/job/30673694721
