### ISSUE TITLE
Operator hangs / Only works at startup

### ISSUE THREAD

**Issue by david-garcia-garcia** [zakkg3/ClusterSecret#136]
Have been trying to setup replication using ClusterSecret for a while and this is my experience:

The operator hangs after a few *minutes*, which results in:

- Replication stops working completely
- ClusterSecret's cannot be removed because the finalizer is stuck

Looks like the operator only works during boot process. Kill the POD for the operator to trigger a sync or release the stuck finalizers for cluster secrets.

Also, the fact that it uses KOPF automatically decorated my whole cluster with annotations that I now need to handle through provider ignores in terraform to avoid removing them.

This was added a few weeks ago to KOPF docs:

> Please do not use Kopf, it is a nightmare of controller bad practices and some of its implicit behaviors will annihilate your API server. The individual handler approach it encourages is the exact opposite of how you should write a Kubernetes controller. Like fundamentally it teaches you the exact opposite mindset you should be in. Using Kopf legitimately has taken years off my life and it took down our clusters several times because of poor code practices on our side and sh***y defaults on its end. We have undergone the herculean effort to move all our controllers to pure golang and the result has been a much more stable ecosystem. /[Jmc_da_boss](https://www.reddit.com/r/kubernetes/comments/1dge5qk/comment/l8qbbll/)/

For anyone looking for a replication solution, I found the following alternatives which are actually mentioned in the cert-manager docs:

* https://github.com/mittwald/kubernetes-replicator
* https://github.com/emberstack/kubernetes-reflector

And also this one:

* https://github.com/config-syncer/config-syncer

**Comment by zakkg3** [comment]
I can not reproduce.

please provide steps to reproduce this.
