### ISSUE TITLE
typo in install instructions in official site

### ISSUE THREAD

**Issue by ilan07m** [zakkg3/ClusterSecret#137]
hi, in the official site: https://clustersecret.io/ , in the https://clustersecret.io/install/ page under install instructions --> Using the official helm chart, there is a typo: 
current: helm repo add clutersecret https://charts.clustersecret.io/
wanted: helm repo add clu***s***tersecret https://charts.clustersecret.io/
this typo causing the error: "Error: INSTALLATION FAILED: repo clustersecret not found" when running the helm install command, in the github repo the install instructions are without the typo

**Comment by zakkg3** [comment]
the official site is .com now.
please open a pr with the corrections.  Thanks!
