### ISSUE TITLE
Unable to install the clustersecret helm chart

### ISSUE THREAD

**Issue by damey2011** [zakkg3/ClusterSecret#138]
Before I now, I didn't have any problems using the cluster secret helm chart, but suddenly I have problems installing it.

```shell
Exception: invoke of kubernetes:helm:template failed: invocation of kubernetes:helm:template returned an error: 
failed to generate YAML for specified Helm chart: failed to pull chart: 
looks like "https://charts.clustersecret.io/" is not a valid chart repository or cannot be reached: 
Get "https://charts.clustersecret.io/index.yaml": dial tcp: lookup charts.clustersecret.io on 67.207.67.2:53: no such host
```

And when I do a nslookup on the domain:

```shell
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find charts.clustersecret.io: NXDOMAIN
```

Is something wrong with the domain?

I understand it's not free to use domains like the `clustersecret.io`, maybe it can just be hosted on the github domains?

**Comment by ThisIsIPat** [comment]
same issue here

**Comment by zoispag** [comment]
Renovatebot complains as well.

<img width="653" alt="image" src="https://github.com/zakkg3/ClusterSecret/assets/21138205/a87c319c-7758-4a26-b313-10a010a87b3e">

**Comment by LoricAndre** [comment]
Same here, it seems like it is a DNS issue, as the main website cannot be resolved either.

**Comment by damey2011** [comment]
A workaround right now is to use it directly from github. Do an helm install directly from repo as `https://raw.githubusercontent.com/zakkg3/ClusterSecret/cluster-secret-0.4.1/docs/` where `cluster-secret-0.4.1` is the branch / tag. No need to specify the version anymore to helm unless you get an error of the version not existing - no version resolution needs to take place anymore since you already specified in the URL.

**Comment by duchuyvp** [comment]
Domain problem is still unsolve?

**Comment by Montralis** [comment]
Im not sure if this Repo is maintained anymore ... It is a nice project

**Comment by Montralis** [comment]
@ThisIsIPat hahah same here, replicator might be the better option, since one can control the ns that gets the secret + other ressources are also shareable

**Comment by zakkg3** [comment]
https://github.com/zakkg3/ClusterSecret/issues/139
