### ISSUE TITLE
clustersecret.io domain expired June 1 2024

### ISSUE THREAD

**Issue by jstewart612** [zakkg3/ClusterSecret#139]
Causes install instructions to not work as is.  Obviously can mirror chart internally but would prefer to source from the source here.

**Comment by jstewart612** [comment]
![image](https://github.com/user-attachments/assets/7d34a37e-48e6-4741-bb7c-cda15f85e9c7)

**Comment by trashhead** [comment]
Is there a workaround?

**Comment by zakkg3** [comment]
Ive registered .com working on the changes now.


clustersecret.com

**Comment by zakkg3** [comment]
> Ive registered .com working on the changes now.
> 
> clustersecret.com

done https://charts.clustersecret.com/  is available with latest version (just bumped up)

**Comment by zakkg3** [comment]
run
```
helm repo remove clustersecret
helm repo add clustersecret https://charts.clustersecret.com/
```
