### ISSUE TITLE
Deploying a ClusterSecret with ArgoCD result in copied Secrets being OutOfSync

### ISSUE THREAD

**Issue by harmathy** [zakkg3/ClusterSecret#146]
The operator copies (most) annotations and labels from the `ClusterSecret` to the copied `Secret`. This includes the label `app.kubernetes.io/instance` which is used by ArgoCD to [track][4] resources. 

Therefore ArgoCD consideres the copied Secret belonging to the *Application* of the `ClusterSecret`. While the `ClusterSecret` itself is deployed by ArgoCD the copied `Secret` is not and thus is considered [`OutOfSync`][10] and will be removed by ArgoCD on a sync with pruning enabled.

[4]: https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/
[10]: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#diffing-customization

**Comment by mihaigalos** [comment]
Hi @harmathy,
I guess you containerized clustersecret and deployed a version with this fix. Can you show the before and after result?
Would probably speed up merging this PR.
