### ISSUE TITLE
Still can't seem to sync new namespaces

### ISSUE THREAD

**Issue by AnsonT** [zakkg3/ClusterSecret#17]
I'm using 0.0.5, it still seems like new namespaces can't be sync'd. I'm using K3S on bare metal. When I add a new namespace to the cluster secret resource that was created after clustersecret, I get the following errors in the log:

`[2020-11-06 07:31:27,430] kopf.reactor.queuein [ERROR   ] functools.partial(<function process_resource_event at 0x7efcf39a5d40>, lifecycle=<function asap at 0x7efcf3bc2710>, registry=<kopf.toolkits.legacy_registries.SmartGlobalRegistry object at 0x7efcf25b3b10>, settings=OperatorSettings(logging=LoggingSettings(), posting=PostingSettings(enabled=True, level=20), watching=WatchingSettings(server_timeout=None, client_timeout=None, connect_timeout=None, reconnect_backoff=0.1), batching=BatchingSettings(worker_limit=None, idle_timeout=5.0, batch_window=0.1, exit_timeout=2.0), execution=ExecutionSettings(executor=<concurrent.futures.thread.ThreadPoolExecutor object at 0x7efcf25b3650>, _max_workers=None), background=BackgroundSettings(cancellation_polling=60, instant_exit_timeout=None, instant_exit_zero_time_cycles=10), persistence=PersistenceSettings(finalizer='kopf.zalando.org/KopfFinalizerMarker', progress_storage=<kopf.storage.progress.SmartProgressStorage object at 0x7efcf25b37d0>, diffbase_storage=<kopf.storage.diffbase.AnnotationsDiffBaseStorage object at 0x7efcf2611fd0>)), memories=<kopf.structs.containers.ResourceMemories object at 0x7efcf26172d0>, resource=Resource(group='', version='v1', plural='namespaces'), event_queue=<Queue at 0x7efcf2617710 maxsize=0 _getters[1] tasks=82>) failed with an exception. Ignoring the event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/queueing.py", line 187, in worker
    await processor(raw_event=raw_event, replenished=replenished)
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/processing.py", line 204, in process_resource_event
    replenished=replenished,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/processing.py", line 227, in apply_reaction_outcomes
    await patching.patch_obj(resource=resource, patch=patch, body=body)
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/auth.py", line 45, in wrapper
    return await fn(*args, **kwargs, context=context)
  File "/usr/local/lib/python3.7/site-packages/kopf/clients/patching.py", line 67, in patch_obj
    raise_for_status=True,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 588, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://10.43.0.1:443/api/v1/namespaces/elk/status')`

**Comment by meezaan** [comment]
Related to this is the issue of deleting a secret after a new namespace is added.

I'm unable to delete these. The secrets disappear (except for the one that got added to the new namespace), but the Custom Resource still stays and the CRD cannot be deleted.

**Comment by andre-lx** [comment]
Hi. 

I'm also getting this issue. 

After some debugging, I came to conclusion that this is some issue with RBAC permissions:

```
export TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
curl -H "Authorization: Bearer $TOKEN" https://kubernetes:443/api/v1/namespaces/NEW_NAMESPACE/status --insecure
```

Results in:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "namespaces "NEW_NAMESPACE" is forbidden: User "system:serviceaccount:clustersecret:clustersecret-account" cannot get resource "namespaces/status" in API group "" in the namespace "NEW_NAMESPACE"",
  "reason": "Forbidden",
  "details": {
    "name": "NEW_NAMESPACE",
    "kind": "namespaces"
  },
  "code": 403
```

After inserting the `"namespaces/status" in API group ""`, the curl executes successfully;

```
{
  "kind": "Namespace",
  "apiVersion": "v1",
  "metadata": {
    "name": "NEW_NAMESPACE",
    "selfLink": "/api/v1/namespaces/NEW_NAMESPACE/status",
    "uid": "...",
    "resourceVersion": "...",
    "creationTimestamp": "...",
    "annotations": {
      "kopf.zalando.org/last-handled-configuration": "{"spec": {"finalizers": ["kubernetes"]}}"
    }
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Active"
  }
```

And if you create a new namespace:

```
kubectl create namespace NEW_NAMESPACE
```

The `handlers.py` executes without this issue.
