### ISSUE TITLE
Bad array iterator

### ISSUE THREAD

**Issue by andre-lx** [zakkg3/ClusterSecret#19]
Hi. 

Using the follow configuration, you get the secret deployed to namespaces that are part of the avoidNamespaces list:

```
matchNamespace:
  - '.*'
avoidNamespaces:
  - 'default'
  - 'auth'
  - 'cert-manager'
  - 'kube-system'
  - 'kube-public'
```

In the follow array, since you are modifying the list while you are iterating it, some of the elements get lost, because of current "pointer". 

```
    # purge
    for ns in matchedns:
        if ns in avoidedns:
            matchedns.remove(ns)

    return matchedns
```

**Comment by zakkg3** [comment]
Thanks for your PR!
