### ISSUE TITLE
Forbidden errors

### ISSUE THREAD

**Issue by paiou** [zakkg3/ClusterSecret#2]
Hello,

First of all thanks for this great initiative.
I'm struggling to make it work, the pod is constantly failing with 403 errors, of two kinds:
- aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://10.32.0.1:443/api/v1/namespaces')
- aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://10.32.0.1:443/apis/clustersecret.io/v1/clustersecrets')

RBAC setup worked fine, but seems still some permissions issue I'm not able to solve.

Thanks in advance for your help.

**Comment by zakkg3** [comment]
Hi @paiou 
I need more information to reproduce it.
Can you please paste the whole error. When it throw this exception, on startup?
Also kubectl --version

Ty

**Comment by Rockmaclu** [comment]
I am also experimenting the same problem.

Here is the full log.

> [2020-05-21 13:15:32,094] kopf.reactor.activit [INFO ] Initial authentication has been initiated.
> [2020-05-21 13:15:32,096] kopf.activities.auth [INFO ] Activity 'login_via_pykube' succeeded.
> [2020-05-21 13:15:32,098] kopf.activities.auth [INFO ] Activity 'login_via_client' succeeded.
> [2020-05-21 13:15:32,099] kopf.reactor.activit [INFO ] Initial authentication has finished.
> [2020-05-21 13:15:32,117] kopf.engines.peering [WARNING ] Default peering object not found, falling back to the standalone mode.
> [2020-05-21 13:15:32,122] kopf.reactor.running [ERROR ] Root task 'watcher of clustersecrets.clustersecret.io' is failed: 403, message='Forbidden', url=URL('https://10.43.0.1:443/apis/clustersecret.io/v1/clustersecrets')
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 453, in _root_task_checker
> await coro
> File "/usr/local/lib/python3.7/site-packages/kopf/reactor/queueing.py", line 109, in watcher
> async for raw_event in stream:
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/watching.py", line 75, in infinite_watch
> async for raw_event in stream:
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/watching.py", line 112, in streaming_watch
> async for raw_event in stream:
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/watching.py", line 130, in continuous_watch
> items, resource_version = await fetching.list_objs_rv(resource=resource, namespace=namespace)
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/auth.py", line 45, in wrapper
> return await fn(*args, **kwargs, context=context)
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/fetching.py", line 101, in list_objs_rv
> response.raise_for_status()
> File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
> headers=self.headers)
> aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://10.43.0.1:443/apis/clustersecret.io/v1/clustersecrets')
> [2020-05-21 13:15:32,125] kopf.reactor.running [WARNING ] Root task 'daemon killer' is finished unexpectedly.
> Traceback (most recent call last):
> File "/usr/local/bin/kopf", line 8, in <module>
> sys.exit(main())
> File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
> return self.main(*args, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
> rv = self.invoke(ctx)
> File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
> return callback(*args, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 36, in wrapper
> return fn(*args, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
> return ctx.invoke(f, obj, *args, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
> return callback(*args, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/kopf/cli.py", line 87, in run
> vault=__controls.vault,
> File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 117, in run
> vault=vault,
> File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
> return future.result()
> File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 161, in operator
> await run_tasks(operator_tasks, ignored=existing_tasks)
> File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 370, in run_tasks
> await _reraise(root_done | root_cancelled | hung_done | hung_cancelled)
> File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 437, in _reraise
> task.result() # can raise the regular (non-cancellation) exceptions.
> File "/usr/local/lib/python3.7/site-packages/kopf/reactor/running.py", line 453, in _root_task_checker
> await coro
> File "/usr/local/lib/python3.7/site-packages/kopf/reactor/queueing.py", line 109, in watcher
> async for raw_event in stream:
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/watching.py", line 75, in infinite_watch
> async for raw_event in stream:
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/watching.py", line 112, in streaming_watch
> async for raw_event in stream:
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/watching.py", line 130, in continuous_watch
> items, resource_version = await fetching.list_objs_rv(resource=resource, namespace=namespace)
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/auth.py", line 45, in wrapper
> return await fn(*args, **kwargs, context=context)
> File "/usr/local/lib/python3.7/site-packages/kopf/clients/fetching.py", line 101, in list_objs_rv
> response.raise_for_status()
> File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
> headers=self.headers)
> aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://10.43.0.1:443/apis/clustersecret.io/v1/clustersecrets')

kubectl version.

> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by paiou** [comment]
Same stack trace for me.

kubectl version:
`Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}                                        Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by zakkg3** [comment]
@paiou @Rockmaclu Thanks for reporting. With  https://github.com/zakkg3/ClusterSecret/pull/4 rbac issues has been addressed. I can not reproduce them anymore.  feel free to reopen if you found something else.
