### ISSUE TITLE
ClusterSecret doesn't apply secret in newly created namespaces

### ISSUE THREAD

**Issue by wijnandtop** [zakkg3/ClusterSecret#22]
**Usecase**
TLS wildcard certificate which needs to be available in all, including newly created, namespaces.

**Issue**
I've applied the yaml files as instructed on a RBAC enables AKS cluster.
When the clustersecret pod starts it does apply the ClusterSecret on all namespaces.
But when a namespace is created, the ClusterSecret isn't applied to this namespace.

It looks like it is missing the events of namepspace creation. But I don't have a clue on how to debug this.

**Workaround**
Obviously not desired; delete pod and during start of the pod it applies secrets to all namespaces matching the given pattern.

**Expected behaviour**
When a new namespace is created the ClusterSecret is applied to this namespace as well.

**yaml**
```
apiVersion: clustersecret.io/v1
type: kubernetes.io/tls
metadata:
  namespace: clustersecret
  name: wildcard-dev-x
matchNamespace:
  - "content"
  - ".*"
data:
  tls.crt: X
  tls.key: X
```

**Logs**
In the output of the ClusterSecret pod I only find ERROR similar to this one:

```
[2021-01-11 19:06:20,450] kopf.objects         [ERROR   ] [None/content-admin-backend-22957138-staging] Handler 'namespace_watcher' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 266, in execute_handler_once
    lifecycle=lifecycle,  # just a default for the sub-handlers, not used directly.
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/handling.py", line 363, in invoke_handler
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/kopf/reactor/invocation.py", line 125, in invoke
    result = await fn(*args, **kwargs)  # type: ignore
  File "/src/handlers.py", line 172, in namespace_watcher
    return {'syncedns': ns_new_list}
UnboundLocalError: local variable 'ns_new_list' referenced before assignment
```

Let me know if you need more details (and how to retrieve them).

**Comment by andre-lx** [comment]
Hi @wijnandtop .

I can't replicate your issue. 

The official image is not updated. You can try this one:

`ydata/clustersecret:0.0.5-fix`

After testing with the following example, everything works well:

```
apiVersion: clustersecret.io/v1
kind: ClusterSecret
type: kubernetes.io/tls
metadata:
  namespace: clustersecret
  name: wildcard-dev-x
matchNamespace:
  - "content"
  - ".*"
data:
  tls.crt: LS0tLS....
  tls.key: LS0tLS1CR.....c1B6YzNsWXlsU0Nv...S0tLS0tCg==
```

After creating a new namespace:

```
[INFO] [None/test] cloning secret in namespace test
[INFO] [None/test] Handler 'namespace_watcher' succeeded.
[INFO] [None/test] All handlers succeeded for creation.
```

If you don't have the debug mode onde, please enable it and post the full result where, please:

https://github.com/zakkg3/ClusterSecret/blob/c21584b932aa2bb7dea95f993ca2d7b0a624d224/yaml/02_deployment.yaml#L25-L30

**Comment by zakkg3** [comment]
As @andre-lx mentioned thi should be fixed with latest pr's merged.
Version updated to 0.0.6 with latest changes. also the deployment. 
release here: https://github.com/zakkg3/ClusterSecret/releases/tag/0.0.6
Try again with this release and let us know if you still see this problem.

**Comment by pancernik** [comment]
I noticed the same error when running `0.0.6`. It created required secrets after a restart. Unfortunately, there was nothing in the logs that would indicate any problems.
