### ISSUE TITLE
Does it have helm chart for declarative installation?

### ISSUE THREAD

**Issue by d1mnewz** [zakkg3/ClusterSecret#23]
eom

**Comment by zakkg3** [comment]
Not for now. but it may be a good idea.

**Comment by patrungel** [comment]
Done that: https://artifacthub.io/packages/helm/patrungel/clustersecret

**Comment by zakkg3** [comment]
@patrungel Nice!
Can you create a pr adding a folder "chart" with it inside. so we can review / co-maintain that guy.
ty

**Comment by zakkg3** [comment]
> Done that: https://artifacthub.io/packages/helm/patrungel/clustersecret

its now served by this repo.

https://artifacthub.io/packages/helm/clutersecret/cluster-secret

**Comment by zakkg3** [comment]
@patrungel Do you want to co-maintain the chart ?

**Comment by patrungel** [comment]
@zakkg3 , sure, will be happy to.
