### ISSUE TITLE
Allow secrets to be copied from approved source namespace only

### ISSUE THREAD

**Issue by maunavarro** [zakkg3/ClusterSecret#25]
Could it be possible to limit the source Secret or ConfigMap used by ClusterSecret to a namespace? For example, only want ClusterSecret to copy a source Secret to other namespaces ONLY if it comes from a specific namespace.

This would be for security reasons as you wouldn't want any user with access to a namespace to apply the correct annotations and copy those secrets to other namespaces (spamming other namespaces).

I'm assuming this would have to be enabled in the controller via the values files.

Couldn't find this feature in the latest release .

**Comment by zakkg3** [comment]
Yes, you can do this by with RBAC roles. 

You may want to replace https://github.com/zakkg3/ClusterSecret/blob/master/yaml/00_rbac.yaml#L43-L46
for a new namespaced role and its correspondient rolebinding.

Here is the official doc:
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

Once you have this working feel free to open a PR with an alternative RBAC.yaml for those who also want this option ;)
Documentation would also be appreciated.

**Comment by zakkg3** [comment]
https://github.com/zakkg3/ClusterSecret/commit/c7fb2054eb419d4e1f18dfea9c773a25b1daf16f
