### ISSUE TITLE
Not working on ARM architectue

### ISSUE THREAD

**Issue by jeromba6** [zakkg3/ClusterSecret#27]
Could you build the docker image also for ARM architecture? Currently it doesn't run on my Raspberry Pi.
 :-( 

`kubectl -n clustersecret logs clustersecret-5f98958756-mxs8b`
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by zakkg3** [comment]
@jeromba6 can you test it?

https://github.com/zakkg3/ClusterSecret/#step-by-step

```
git pull 
kubectl apply -f yaml/arm32v7/02_deployment.yam
```

are u using k3s ?
