### ISSUE TITLE
CRD is defined in templates

### ISSUE THREAD

**Issue by Poundex** [zakkg3/ClusterSecret#70]
The CRD in the Helm Chart is under the templates directory. This means that Helm does not make sure the CRD is installed before any resources, and therefore a chart that has ClusterSecret as a sub-chart cannot create resources of type ClusterSecret as it does not exist at template apply time. 

Would it please be possible to move the CRD definition into the [CRD directory](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) and publish a new version?

Thanks.

**Comment by patrungel** [comment]
Meanwhile I released a new version for https://patrungel.github.io/helm-charts/ (it is meant to be superceded by the helm chart from this project one day) which addresses this issue.
