### ISSUE TITLE
ClusterSecret doesn't create secret across all namespaces

### ISSUE THREAD

**Issue by jurim76** [zakkg3/ClusterSecret#72]
Documentation says that 
"You can specify multiple matching or non-matching RegExp. By default it will match all, same as defining matchNamespace = *"

I'm using the following ClusterSecret manifest to create secret in all namespaces

kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
  name: regcred-secret
avoidNamespaces:
  \- default
data:
  \<some secret here\>

kubectl -n test apply -f clustersecret.yaml

and pod throws the error
`Handler 'create_fn' failed with an exception`

Full error here
https://pastebin.com/SeEFsUUe

**Comment by patrungel** [comment]
Hi, I can confirm that this is not a valid regex, and the operator uses a wrong default value (and no validation whatsoever). As a work-around I'd suggest using `.*` (dot-star) value to match all namespaces.

**Comment by zakkg3** [comment]
fixed by #88
