### ISSUE TITLE
Chart name is camel case.

### ISSUE THREAD

**Issue by cl-christschantz** [zakkg3/ClusterSecret#73]
The chart "ClusterSecret" is not usable as a dependency chart because its in camel case. "cluster-secret" is able to be used however. Both are available via your chart index file:
https://charts.clustersecret.io/index.yaml

Best practice says chart names must be lowercase letters and numbers:

https://helm.sh/docs/chart_best_practices/conventions/

Thanks!

**Comment by ecsimsw** [comment]
For those who need to use it right now. 
Installing without helm is fine.

```
git clone https://github.com/zakkg3/ClusterSecret.git
kubectl apply -f ClusterSecret/yaml
```

**Comment by theGC** [comment]
to use helm prior to the [PR](https://github.com/zakkg3/ClusterSecret/pull/75):

```
helm install clustersecret clutersecret/ClusterSecret --version 0.1.1 -n clustersecret --create-namespace --set fullnameOverride=cluster-secret
```

**Comment by patrungel** [comment]
Meanwhile I released a new version for https://patrungel.github.io/helm-charts/ (it is meant to be superceded by the helm chart from this project one day).

**Comment by mig4ng** [comment]
Thanks @theGC , that worked. If anyone is installing this with Terraform, take this example:
```
resource "helm_release" "cluster_secret" {
  name        = "clutersecret"
  repository  = "https://charts.clustersecret.io/"
  chart       = "ClusterSecret"
  namespace   = "clutersecret"
  version = "0.1.1"
  create_namespace = true

  set {
    name  = "fullnameOverride"
    value = "cluster-secret"
  }
}
```

Soon this might not be necessary if https://github.com/zakkg3/ClusterSecret/pull/75 gets merged.
