### ISSUE TITLE
No support for secret type

### ISSUE THREAD

**Issue by jurim76** [zakkg3/ClusterSecret#74]
Only Opaue type is supported

**Comment by patrungel** [comment]
Hey @jurim76  can you please specify the operator version you are running as well as the example `clustersecret` CR that reproduces the issue?
The CRD supports [type](https://github.com/zakkg3/ClusterSecret/blob/master/yaml/01_crd.yaml#L25) field that defaults to `Opaque` and is totally configurable.

**Comment by jurim76** [comment]
Sorry, missed that
