### ISSUE TITLE
kopf._core.reactor.o: Not enough permissions to watch for resources

### ISSUE THREAD

**Issue by ravi-devarakonda** [zakkg3/ClusterSecret#76]
Hello,

Creating an issue here based on the suggestion from the slack channel.

We recently deployed the Cluster Secret Operator `v0.0.9` to one of our GKE clusters and I see a couple of issues..

At the start of the pod logs I see:

```
kopf._core.reactor.o [WARNING ] Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts.
```
and later after the sync happens, I see an error:

```
Patching failed with inconsistencies: (('remove', ('status', 'namespace_watcher'), {'syncedns':['ns1', 'ns2']}, None),)
```

We used the helm chart for the deployment and default values.

Any help is appreciated.

Best Regards,
Ravi

**Comment by axel7083** [comment]
Same warning here

**Comment by axel7083** [comment]
I was able to fix the warning by changing the following

https://github.com/zakkg3/ClusterSecret/blob/d212216d4263e1f4829817864559af6981ee6819/yaml/00_rbac.yaml#L21

with 
```yaml
 - apiGroups: [apiextensions.k8s.io]
```

**Comment by patrungel** [comment]
Meanwhile I released a new version for https://patrungel.github.io/helm-charts/ (it is meant to be superceded by the helm chart from this project one day) which addresses this issue.

**Comment by ravi-devarakonda** [comment]
Thank you very much @axel7083 and @patrungel!

**Comment by mig4ng** [comment]
Hi @zakkg3 , any news about when will we have a new release to have this issue solved in the latest release?
I am needing it atm, it would be very helpful 😄

**Comment by zakkg3** [comment]
Release comming soon. we are working on some improvements

**Comment by zakkg3** [comment]
fixed here https://github.com/zakkg3/ClusterSecret/pull/109
