### ISSUE TITLE
Add labels in the metadata of the created secrets

### ISSUE THREAD

**Issue by amine7777** [zakkg3/ClusterSecret#80]
Is it possible to add labels in the created secret pls..I thought when you add labels inside the clustersecret manifest it will also add the labels in the generated secret but I have tried and it doesn't work.

My assumption is to maybe add them here if I am correct..

`

        for ns in syncedns:
            logger.info(f'Re Syncing secret {name} in ns {ns}')
            metadata = {'name': name, 'namespace': ns, 'labels': labels } # HERE
            api_version = 'v1'
            kind = 'Secret'
            data = new
            body = client.V1Secret(
                api_version=api_version,
                data=data ,
                kind=kind,
                metadata=metadata,
                type = secret_type
            )
            response = v1.replace_namespaced_secret(name,ns,body)
            logger.debug(response)

**Comment by axel7083** [comment]
It should be added inside the `sync_secret` section

https://github.com/zakkg3/ClusterSecret/blob/6b6a562c23d9c9d9886fec3c5ac994996ac3db99/src/csHelper.py#L231-L234


The section you extracted and quoted has the following decorator `@kopf.on.field('clustersecret.io', 'v1', 'clustersecrets', field='data')`. Meaning it will be called only when the data will changes.

If the desire behavior is to support propagating the labels and annotations on creation, the code should be added in the section I quoted. If the labels should be keep sync, then two new functions should be created with field='metadata.labels' and field=`metadata.annotation`
