### ISSUE TITLE
Latest chart not available via index.yaml

### ISSUE THREAD

**Issue by cl-christschantz** [zakkg3/ClusterSecret#84]
The latest chart you published (0.2.1) is not available in your official index.yaml:

https://charts.clustersecret.io/index.yaml

I can see its in the [gh-pages](https://raw.githubusercontent.com/zakkg3/ClusterSecret/gh-pages/index.yaml) repo, but for some reason its not updated in charts.clustersecret.io.

Issue:
```
helm repo add clustersecret https://charts.clustersecret.io/
helm search repo clustersecret
```

Undesired output:
```
NAME                            CHART VERSION   APP VERSION     DESCRIPTION           
clustersecret/ClusterSecret     0.1.1           0.0.9           ClusterSecret Operator
clustersecret/cluster-secret    0.1.0           0.8.0           ClusterSecret Operator
```

**Comment by patrungel** [comment]
I guess it's just taking time to update, the index.yaml got generated a-okay.

**Comment by mig4ng** [comment]
Hi, I have the same issue, on the release day I thought it was just taking time, but it still did not update.

Not sure if anything broke on the publish or it still cached...

https://github.com/orgs/community/discussions/49753#discussioncomment-5273359

@zakkg3 leaving this here as it might be interesting to disable caching or re-trigger a deploy. Thanks :)

**Comment by zakkg3** [comment]
Ah  sorry forgot to push the branch gh-pages where the charts are actually been serrved.

now it works:

```
helm install clustersecret clustersecret/cluster-secret --version 0.2.1 -n clustersecret --create-namespace

NAME: clustersecret
LAST DEPLOYED: Mon Sep  4 13:11:05 2023
NAMESPACE: clustersecret
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by zakkg3** [comment]
solved by https://github.com/zakkg3/ClusterSecret/commit/35145070abb7bca81705e0afc88ac9527d774db5
